processes:
  ollama:
    command: bash ./scripts/run-ollama.sh
    restart: always
    readiness_probe:
      exec:
        command: sh -c "curl -s http://localhost:11434/api/tags"
      interval: 2s
      retries: 60

  ensure-models:
    depends_on:
      ollama:
        condition: process_healthy
    command: bash ./scripts/ensure-models.sh
    restart: "no"

  openwebui:
    depends_on:
      ensure-models:
        condition: process_completed
      ollama:
        condition: process_healthy
    command: >
      sh -c "
          docker rm -f open-webui >/dev/null 2>&1 || true && 
          docker run --rm \
            --name open-webui \
            --network ollama-net \
            --no-healthcheck \
            -p 3000:8080 \
            -e OLLAMA_BASE_URL=http://ollama:11434 \
            -v openwebui_data:/app/backend/data \
            'ghcr.io/open-webui/open-webui:main'
      "
    restart: always
